message ("ADOLC_ROOT is ${ADOLC_ROOT}")
ExternalProject_Add(ADOLC
  PREFIX        ${ADOLC_BINARY_DIR}
  TMP_DIR       ${ADOLC_ROOT}/tmp
  STAMP_DIR     ${ADOLC_ROOT}/tmp/stamp
  SOURCE_DIR    ${ADOLC_ROOT}
  BUILD_IN_SOURCE 1
  DOWNLOAD_COMMAND "true"
  CONFIGURE_COMMAND  ${ADOLC_ROOT}/configure --prefix=${ADOLC_BINARY_DIR} ${ADOLC_CONFIGURE_FLAGS}
  BUILD_COMMAND make all ${EXTERNAL_PROJECT_BUILD_FLAGS}
  INSTALL_COMMAND make install
)
